### ISSUE TITLE
Center gallery

### ISSUE THREAD

**Issue by guilhermegarcia** [royfrancis/pixture#2]
I've been trying to center the gallery but can't seem to figure it out. I've tried specifying that in my CSS file, but no success.

```
.html-widget {
    margin: auto;
}
```

**Comment by guilhermegarcia** [comment]
Solution: add this to your own css file (I took this from `pixture.css`, which is the stylesheet used and reset every time the `rmd` file is compile, so changing it there isn't very practical).

```
.pixture-gallery {
 display: flex;
 flex-direction: row;
 flex-wrap: wrap;
 justify-content: center;
 align-items: stretch;
 align-content: stretch;
 margin: 1em 0;
}
```

**Comment by royfrancis** [comment]
I have updated the code to the use the images through `img` tags rather than `background`. This in a way fixes the centering issue as well since the gallery now takes up the full available width.
