### ISSUE TITLE
Update package to new R version

### ISSUE THREAD

**Issue by leticiamicheli** [royfrancis/pixture#3]
Hi there, 

I use pixture for my personal website and I really enjoy this package. I have recently updated R and unfortunately pixture is not available for the newest versions of R. 

Is there a plan to update the package?

Thank you very much!

**Comment by royfrancis** [comment]
Do you mean R 4.2? Are there any issues during installation?

**Comment by leticiamicheli** [comment]
Hi there, 

thanks for the reply. I am currently using R 4.1.2.

When trying to install pixture I got a warning message that "package ‘pixture’ is not available for this version of R". But I got it to work by remoting installing it (remotes::install_github('royfrancis/pixture')).

Thank you.

**Comment by royfrancis** [comment]
Ah ok. If you tried to install from CRAN, of course it's not available there. It has to be installed from GitHub as you did.
